name: Deploy Prod

on:
  push:
    branches: ["prod"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image and push
        run: docker buildx build . --file WebApi/Dockerfile --tag techgadget/techgadget-prod --push

      - name: Setup SSH Keys
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2 part 4 (Deploy Server)
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP_PROD }} << EOF
            sudo docker pull techgadget/techgadget-prod
            sudo docker stop techgadget-prod || true
            sudo docker rm techgadget-prod || true
            sudo docker run -e ASPNETCORE_ENVIRONMENT=Production -d --hostname host-techgadget-prod --name techgadget-prod --network my_network -p 5000:8080 techgadget/techgadget-prod
            sudo docker rmi $(sudo docker images -f "dangling=true" -q) || true
          EOF